// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GamesProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameProtocol {

  /// <summary>Holder for reflection information generated from GamesProtocol.proto</summary>
  public static partial class GamesProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for GamesProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GamesProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNHYW1lc1Byb3RvY29sLnByb3RvEgxHYW1lUHJvdG9jb2wiogMKCE1haW5Q",
            "YWNrEi4KC3JlcXVlc3RDb2RlGAEgASgOMhkuR2FtZVByb3RvY29sLlJlcXVl",
            "c3RDb2RlEiwKCmFjdGlvbkNvZGUYAiABKA4yGC5HYW1lUHJvdG9jb2wuQWN0",
            "aW9uQ29kZRIsCgpyZXR1cm5Db2RlGAMgASgOMhguR2FtZVByb3RvY29sLlJl",
            "dHVybkNvZGUSDgoGc3RyTXNnGAQgASgJEiwKCWxvZ2luUGFjaxgFIAEoCzIX",
            "LkdhbWVQcm90b2NvbC5Mb2dpblBhY2tIABIqCghjaGF0UGFjaxgGIAEoCzIW",
            "LkdhbWVQcm90b2NvbC5DaGF0UGFja0gAEi4KCmZyaWVuZFBhY2sYByABKAsy",
            "GC5HYW1lUHJvdG9jb2wuRnJpZW5kUGFja0gAEjgKD2NoYXRIaXN0b3J5UGFj",
            "axgIIAEoCzIdLkdhbWVQcm90b2NvbC5DaGF0SGlzdG9yeVBhY2tIABIuCgpi",
            "YXR0bGVQYWNrGAkgASgLMhguR2FtZVByb3RvY29sLkJhdHRsZVBhY2tIAEIG",
            "CgRkYXRhIi8KCUxvZ2luUGFjaxIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNz",
            "d29yZBgCIAEoCSJiCghDaGF0UGFjaxIOCgZ0b1VzZXIYASABKAkSEAoIZnJv",
            "bVVzZXIYAiABKAkSDwoHY29udGVudBgDIAEoCRIQCghjaGF0VHlwZRgEIAEo",
            "BRIRCgl0aW1lc3RhbXAYBSABKAMiQgoKRnJpZW5kSW5mbxIQCgh1c2VybmFt",
            "ZRgBIAEoCRIQCghpc09ubGluZRgCIAEoCBIQCghpc0ZyaWVuZBgDIAEoCCJ6",
            "CgpGcmllbmRQYWNrEioKBm9wVHlwZRgBIAEoDjIaLkdhbWVQcm90b2NvbC5G",
            "cmllbmRPcFR5cGUSEgoKdGFyZ2V0VXNlchgCIAEoCRIsCgpmcmllbmRMaXN0",
            "GAMgAygLMhguR2FtZVByb3RvY29sLkZyaWVuZEluZm8iTwoPQ2hhdEhpc3Rv",
            "cnlQYWNrEhIKCnRhcmdldFVzZXIYASABKAkSKAoIY2hhdExpc3QYAiADKAsy",
            "Fi5HYW1lUHJvdG9jb2wuQ2hhdFBhY2sieAoKQmF0dGxlUGFjaxIPCgdsZXZl",
            "bElkGAEgASgFEhYKDmNhcmRJbnN0YW5jZUlkGAIgASgFEhYKDnRhcmdldEVu",
            "dGl0eUlkGAMgASgFEikKBmV2ZW50cxgEIAMoCzIZLkdhbWVQcm90b2NvbC5C",
            "YXR0bGVFdmVudCKqAgoLQmF0dGxlRXZlbnQSMAoJZXZlbnRUeXBlGAEgASgO",
            "Mh0uR2FtZVByb3RvY29sLkJhdHRsZUV2ZW50VHlwZRIQCghzb3VyY2VJZBgC",
            "IAEoBRIQCgh0YXJnZXRJZBgDIAEoBRIsCgZkYW1hZ2UYBCABKAsyGi5HYW1l",
            "UHJvdG9jb2wuRGFtYWdlUGFyYW1zSAASKAoEaGVhbBgFIAEoCzIYLkdhbWVQ",
            "cm90b2NvbC5IZWFsUGFyYW1zSAASKgoFZGVhdGgYBiABKAsyGS5HYW1lUHJv",
            "dG9jb2wuRGVhdGhQYXJhbXNIABIyCglza2lsbENhc3QYByABKAsyHS5HYW1l",
            "UHJvdG9jb2wuU2tpbGxDYXN0UGFyYW1zSABCDQoLZXZlbnRQYXJhbXMiNwoM",
            "RGFtYWdlUGFyYW1zEhMKC2RhbWFnZVZhbHVlGAEgASgFEhIKCmlzQ3JpdGlj",
            "YWwYAiABKAgiMwoKSGVhbFBhcmFtcxIRCgloZWFsVmFsdWUYASABKAUSEgoK",
            "aXNPdmVySGVhbBgCIAEoCCINCgtEZWF0aFBhcmFtcyI1Cg9Ta2lsbENhc3RQ",
            "YXJhbXMSDwoHc2tpbGxJZBgBIAEoBRIRCgl0YXJnZXRJZHMYAiADKAUqQAoL",
            "UmVxdWVzdENvZGUSDwoLUmVxdWVzdE5vbmUQABIICgRVc2VyEAESCgoGRnJp",
            "ZW5kEAISCgoGQmF0dGxlEAMquQEKCkFjdGlvbkNvZGUSDgoKQWN0aW9uTm9u",
            "ZRAAEgkKBUxvZ29uEAESCQoFTG9naW4QAhINCglIZWFydGJlYXQQAxIPCgtD",
            "aGF0UHJpdmF0ZRAEEhMKD0ZyaWVuZE9wZXJhdGlvbhAFEhIKDkdldENoYXRI",
            "aXN0b3J5EAYSDAoIRW50ZXJQdmUQBxIMCghQbGF5Q2FyZBAIEgsKB0VuZFR1",
            "cm4QCRITCg9TeW5jQmF0dGxlRXZlbnQQCio1CgpSZXR1cm5Db2RlEg4KClJl",
            "dHVybk5vbmUQABILCgdTdWNjZWVkEAESCgoGRmFpbGVkEAIqXgoMRnJpZW5k",
            "T3BUeXBlEhAKDEZyaWVuZE9wTm9uZRAAEgsKB0dldExpc3QQARINCglBZGRG",
            "cmllbmQQAhIQCgxSZW1vdmVGcmllbmQQAxIOCgpTZWFyY2hVc2VyEAQqlgEK",
            "D0JhdHRsZUV2ZW50VHlwZRIICgROb25lEAASDwoLQmF0dGxlU3RhcnQQARIN",
            "CglCYXR0bGVFbmQQAhINCglUdXJuU3RhcnQQChILCgdUdXJuRW5kEAsSDQoJ",
            "U2tpbGxDYXN0EBQSDwoLRGFtYWdlVGFrZW4QHhINCglIZWFsVGFrZW4QHxIO",
            "CgpFbnRpdHlEaWVkECBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameProtocol.RequestCode), typeof(global::GameProtocol.ActionCode), typeof(global::GameProtocol.ReturnCode), typeof(global::GameProtocol.FriendOpType), typeof(global::GameProtocol.BattleEventType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.MainPack), global::GameProtocol.MainPack.Parser, new[]{ "RequestCode", "ActionCode", "ReturnCode", "StrMsg", "LoginPack", "ChatPack", "FriendPack", "ChatHistoryPack", "BattlePack" }, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.LoginPack), global::GameProtocol.LoginPack.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.ChatPack), global::GameProtocol.ChatPack.Parser, new[]{ "ToUser", "FromUser", "Content", "ChatType", "Timestamp" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.FriendInfo), global::GameProtocol.FriendInfo.Parser, new[]{ "Username", "IsOnline", "IsFriend" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.FriendPack), global::GameProtocol.FriendPack.Parser, new[]{ "OpType", "TargetUser", "FriendList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.ChatHistoryPack), global::GameProtocol.ChatHistoryPack.Parser, new[]{ "TargetUser", "ChatList" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.BattlePack), global::GameProtocol.BattlePack.Parser, new[]{ "LevelId", "CardInstanceId", "TargetEntityId", "Events" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.BattleEvent), global::GameProtocol.BattleEvent.Parser, new[]{ "EventType", "SourceId", "TargetId", "Damage", "Heal", "Death", "SkillCast" }, new[]{ "EventParams" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.DamageParams), global::GameProtocol.DamageParams.Parser, new[]{ "DamageValue", "IsCritical" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.HealParams), global::GameProtocol.HealParams.Parser, new[]{ "HealValue", "IsOverHeal" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.DeathParams), global::GameProtocol.DeathParams.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::GameProtocol.SkillCastParams), global::GameProtocol.SkillCastParams.Parser, new[]{ "SkillId", "TargetIds" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RequestCode {
    [pbr::OriginalName("RequestNone")] RequestNone = 0,
    /// <summary>
    ///用户
    /// </summary>
    [pbr::OriginalName("User")] User = 1,
    /// <summary>
    ///好友
    /// </summary>
    [pbr::OriginalName("Friend")] Friend = 2,
    [pbr::OriginalName("Battle")] Battle = 3,
  }

  public enum ActionCode {
    [pbr::OriginalName("ActionNone")] ActionNone = 0,
    /// <summary>
    ///注册
    /// </summary>
    [pbr::OriginalName("Logon")] Logon = 1,
    /// <summary>
    ///登录
    /// </summary>
    [pbr::OriginalName("Login")] Login = 2,
    /// <summary>
    ///心跳包
    /// </summary>
    [pbr::OriginalName("Heartbeat")] Heartbeat = 3,
    /// <summary>
    ///私聊频道
    /// </summary>
    [pbr::OriginalName("ChatPrivate")] ChatPrivate = 4,
    /// <summary>
    ///好友相关操作
    /// </summary>
    [pbr::OriginalName("FriendOperation")] FriendOperation = 5,
    /// <summary>
    ///获取历史聊天记录
    /// </summary>
    [pbr::OriginalName("GetChatHistory")] GetChatHistory = 6,
    /// <summary>
    ///请求进入单机/PVE关卡
    /// </summary>
    [pbr::OriginalName("EnterPve")] EnterPve = 7,
    /// <summary>
    ///玩家出牌
    /// </summary>
    [pbr::OriginalName("PlayCard")] PlayCard = 8,
    /// <summary>
    ///结束回合
    /// </summary>
    [pbr::OriginalName("EndTurn")] EndTurn = 9,
    /// <summary>
    ///服务端下发战斗表现事件
    /// </summary>
    [pbr::OriginalName("SyncBattleEvent")] SyncBattleEvent = 10,
  }

  public enum ReturnCode {
    [pbr::OriginalName("ReturnNone")] ReturnNone = 0,
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("Succeed")] Succeed = 1,
    /// <summary>
    ///失败
    /// </summary>
    [pbr::OriginalName("Failed")] Failed = 2,
  }

  public enum FriendOpType {
    [pbr::OriginalName("FriendOpNone")] FriendOpNone = 0,
    /// <summary>
    /// 客户端请求获取列表，或服务器返回列表
    /// </summary>
    [pbr::OriginalName("GetList")] GetList = 1,
    /// <summary>
    /// 添加好友
    /// </summary>
    [pbr::OriginalName("AddFriend")] AddFriend = 2,
    /// <summary>
    /// 删除好友
    /// </summary>
    [pbr::OriginalName("RemoveFriend")] RemoveFriend = 3,
    /// <summary>
    ///搜索玩家
    /// </summary>
    [pbr::OriginalName("SearchUser")] SearchUser = 4,
  }

  /// <summary>
  /// 战斗事件类型
  /// </summary>
  public enum BattleEventType {
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    /// 战斗开始
    /// </summary>
    [pbr::OriginalName("BattleStart")] BattleStart = 1,
    /// <summary>
    /// 战斗结束
    /// </summary>
    [pbr::OriginalName("BattleEnd")] BattleEnd = 2,
    /// <summary>
    /// 回合开始
    /// </summary>
    [pbr::OriginalName("TurnStart")] TurnStart = 10,
    /// <summary>
    /// 回合结束
    /// </summary>
    [pbr::OriginalName("TurnEnd")] TurnEnd = 11,
    /// <summary>
    /// 技能释放
    /// </summary>
    [pbr::OriginalName("SkillCast")] SkillCast = 20,
    /// <summary>
    /// 受到伤害
    /// </summary>
    [pbr::OriginalName("DamageTaken")] DamageTaken = 30,
    /// <summary>
    /// 受到治疗
    /// </summary>
    [pbr::OriginalName("HealTaken")] HealTaken = 31,
    /// <summary>
    /// 实体死亡
    /// </summary>
    [pbr::OriginalName("EntityDied")] EntityDied = 32,
  }

  #endregion

  #region Messages
  public sealed partial class MainPack : pb::IMessage<MainPack> {
    private static readonly pb::MessageParser<MainPack> _parser = new pb::MessageParser<MainPack>(() => new MainPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MainPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MainPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MainPack(MainPack other) : this() {
      requestCode_ = other.requestCode_;
      actionCode_ = other.actionCode_;
      returnCode_ = other.returnCode_;
      strMsg_ = other.strMsg_;
      switch (other.DataCase) {
        case DataOneofCase.LoginPack:
          LoginPack = other.LoginPack.Clone();
          break;
        case DataOneofCase.ChatPack:
          ChatPack = other.ChatPack.Clone();
          break;
        case DataOneofCase.FriendPack:
          FriendPack = other.FriendPack.Clone();
          break;
        case DataOneofCase.ChatHistoryPack:
          ChatHistoryPack = other.ChatHistoryPack.Clone();
          break;
        case DataOneofCase.BattlePack:
          BattlePack = other.BattlePack.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MainPack Clone() {
      return new MainPack(this);
    }

    /// <summary>Field number for the "requestCode" field.</summary>
    public const int RequestCodeFieldNumber = 1;
    private global::GameProtocol.RequestCode requestCode_ = global::GameProtocol.RequestCode.RequestNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.RequestCode RequestCode {
      get { return requestCode_; }
      set {
        requestCode_ = value;
      }
    }

    /// <summary>Field number for the "actionCode" field.</summary>
    public const int ActionCodeFieldNumber = 2;
    private global::GameProtocol.ActionCode actionCode_ = global::GameProtocol.ActionCode.ActionNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.ActionCode ActionCode {
      get { return actionCode_; }
      set {
        actionCode_ = value;
      }
    }

    /// <summary>Field number for the "returnCode" field.</summary>
    public const int ReturnCodeFieldNumber = 3;
    private global::GameProtocol.ReturnCode returnCode_ = global::GameProtocol.ReturnCode.ReturnNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.ReturnCode ReturnCode {
      get { return returnCode_; }
      set {
        returnCode_ = value;
      }
    }

    /// <summary>Field number for the "strMsg" field.</summary>
    public const int StrMsgFieldNumber = 4;
    private string strMsg_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StrMsg {
      get { return strMsg_; }
      set {
        strMsg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "loginPack" field.</summary>
    public const int LoginPackFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.LoginPack LoginPack {
      get { return dataCase_ == DataOneofCase.LoginPack ? (global::GameProtocol.LoginPack) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.LoginPack;
      }
    }

    /// <summary>Field number for the "chatPack" field.</summary>
    public const int ChatPackFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.ChatPack ChatPack {
      get { return dataCase_ == DataOneofCase.ChatPack ? (global::GameProtocol.ChatPack) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.ChatPack;
      }
    }

    /// <summary>Field number for the "friendPack" field.</summary>
    public const int FriendPackFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.FriendPack FriendPack {
      get { return dataCase_ == DataOneofCase.FriendPack ? (global::GameProtocol.FriendPack) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.FriendPack;
      }
    }

    /// <summary>Field number for the "chatHistoryPack" field.</summary>
    public const int ChatHistoryPackFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.ChatHistoryPack ChatHistoryPack {
      get { return dataCase_ == DataOneofCase.ChatHistoryPack ? (global::GameProtocol.ChatHistoryPack) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.ChatHistoryPack;
      }
    }

    /// <summary>Field number for the "battlePack" field.</summary>
    public const int BattlePackFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.BattlePack BattlePack {
      get { return dataCase_ == DataOneofCase.BattlePack ? (global::GameProtocol.BattlePack) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.BattlePack;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      LoginPack = 5,
      ChatPack = 6,
      FriendPack = 7,
      ChatHistoryPack = 8,
      BattlePack = 9,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MainPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MainPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestCode != other.RequestCode) return false;
      if (ActionCode != other.ActionCode) return false;
      if (ReturnCode != other.ReturnCode) return false;
      if (StrMsg != other.StrMsg) return false;
      if (!object.Equals(LoginPack, other.LoginPack)) return false;
      if (!object.Equals(ChatPack, other.ChatPack)) return false;
      if (!object.Equals(FriendPack, other.FriendPack)) return false;
      if (!object.Equals(ChatHistoryPack, other.ChatHistoryPack)) return false;
      if (!object.Equals(BattlePack, other.BattlePack)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestCode != global::GameProtocol.RequestCode.RequestNone) hash ^= RequestCode.GetHashCode();
      if (ActionCode != global::GameProtocol.ActionCode.ActionNone) hash ^= ActionCode.GetHashCode();
      if (ReturnCode != global::GameProtocol.ReturnCode.ReturnNone) hash ^= ReturnCode.GetHashCode();
      if (StrMsg.Length != 0) hash ^= StrMsg.GetHashCode();
      if (dataCase_ == DataOneofCase.LoginPack) hash ^= LoginPack.GetHashCode();
      if (dataCase_ == DataOneofCase.ChatPack) hash ^= ChatPack.GetHashCode();
      if (dataCase_ == DataOneofCase.FriendPack) hash ^= FriendPack.GetHashCode();
      if (dataCase_ == DataOneofCase.ChatHistoryPack) hash ^= ChatHistoryPack.GetHashCode();
      if (dataCase_ == DataOneofCase.BattlePack) hash ^= BattlePack.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RequestCode != global::GameProtocol.RequestCode.RequestNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) RequestCode);
      }
      if (ActionCode != global::GameProtocol.ActionCode.ActionNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ActionCode);
      }
      if (ReturnCode != global::GameProtocol.ReturnCode.ReturnNone) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ReturnCode);
      }
      if (StrMsg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(StrMsg);
      }
      if (dataCase_ == DataOneofCase.LoginPack) {
        output.WriteRawTag(42);
        output.WriteMessage(LoginPack);
      }
      if (dataCase_ == DataOneofCase.ChatPack) {
        output.WriteRawTag(50);
        output.WriteMessage(ChatPack);
      }
      if (dataCase_ == DataOneofCase.FriendPack) {
        output.WriteRawTag(58);
        output.WriteMessage(FriendPack);
      }
      if (dataCase_ == DataOneofCase.ChatHistoryPack) {
        output.WriteRawTag(66);
        output.WriteMessage(ChatHistoryPack);
      }
      if (dataCase_ == DataOneofCase.BattlePack) {
        output.WriteRawTag(74);
        output.WriteMessage(BattlePack);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RequestCode != global::GameProtocol.RequestCode.RequestNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) RequestCode);
      }
      if (ActionCode != global::GameProtocol.ActionCode.ActionNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActionCode);
      }
      if (ReturnCode != global::GameProtocol.ReturnCode.ReturnNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ReturnCode);
      }
      if (StrMsg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StrMsg);
      }
      if (dataCase_ == DataOneofCase.LoginPack) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LoginPack);
      }
      if (dataCase_ == DataOneofCase.ChatPack) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatPack);
      }
      if (dataCase_ == DataOneofCase.FriendPack) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FriendPack);
      }
      if (dataCase_ == DataOneofCase.ChatHistoryPack) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatHistoryPack);
      }
      if (dataCase_ == DataOneofCase.BattlePack) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattlePack);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MainPack other) {
      if (other == null) {
        return;
      }
      if (other.RequestCode != global::GameProtocol.RequestCode.RequestNone) {
        RequestCode = other.RequestCode;
      }
      if (other.ActionCode != global::GameProtocol.ActionCode.ActionNone) {
        ActionCode = other.ActionCode;
      }
      if (other.ReturnCode != global::GameProtocol.ReturnCode.ReturnNone) {
        ReturnCode = other.ReturnCode;
      }
      if (other.StrMsg.Length != 0) {
        StrMsg = other.StrMsg;
      }
      switch (other.DataCase) {
        case DataOneofCase.LoginPack:
          if (LoginPack == null) {
            LoginPack = new global::GameProtocol.LoginPack();
          }
          LoginPack.MergeFrom(other.LoginPack);
          break;
        case DataOneofCase.ChatPack:
          if (ChatPack == null) {
            ChatPack = new global::GameProtocol.ChatPack();
          }
          ChatPack.MergeFrom(other.ChatPack);
          break;
        case DataOneofCase.FriendPack:
          if (FriendPack == null) {
            FriendPack = new global::GameProtocol.FriendPack();
          }
          FriendPack.MergeFrom(other.FriendPack);
          break;
        case DataOneofCase.ChatHistoryPack:
          if (ChatHistoryPack == null) {
            ChatHistoryPack = new global::GameProtocol.ChatHistoryPack();
          }
          ChatHistoryPack.MergeFrom(other.ChatHistoryPack);
          break;
        case DataOneofCase.BattlePack:
          if (BattlePack == null) {
            BattlePack = new global::GameProtocol.BattlePack();
          }
          BattlePack.MergeFrom(other.BattlePack);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RequestCode = (global::GameProtocol.RequestCode) input.ReadEnum();
            break;
          }
          case 16: {
            ActionCode = (global::GameProtocol.ActionCode) input.ReadEnum();
            break;
          }
          case 24: {
            ReturnCode = (global::GameProtocol.ReturnCode) input.ReadEnum();
            break;
          }
          case 34: {
            StrMsg = input.ReadString();
            break;
          }
          case 42: {
            global::GameProtocol.LoginPack subBuilder = new global::GameProtocol.LoginPack();
            if (dataCase_ == DataOneofCase.LoginPack) {
              subBuilder.MergeFrom(LoginPack);
            }
            input.ReadMessage(subBuilder);
            LoginPack = subBuilder;
            break;
          }
          case 50: {
            global::GameProtocol.ChatPack subBuilder = new global::GameProtocol.ChatPack();
            if (dataCase_ == DataOneofCase.ChatPack) {
              subBuilder.MergeFrom(ChatPack);
            }
            input.ReadMessage(subBuilder);
            ChatPack = subBuilder;
            break;
          }
          case 58: {
            global::GameProtocol.FriendPack subBuilder = new global::GameProtocol.FriendPack();
            if (dataCase_ == DataOneofCase.FriendPack) {
              subBuilder.MergeFrom(FriendPack);
            }
            input.ReadMessage(subBuilder);
            FriendPack = subBuilder;
            break;
          }
          case 66: {
            global::GameProtocol.ChatHistoryPack subBuilder = new global::GameProtocol.ChatHistoryPack();
            if (dataCase_ == DataOneofCase.ChatHistoryPack) {
              subBuilder.MergeFrom(ChatHistoryPack);
            }
            input.ReadMessage(subBuilder);
            ChatHistoryPack = subBuilder;
            break;
          }
          case 74: {
            global::GameProtocol.BattlePack subBuilder = new global::GameProtocol.BattlePack();
            if (dataCase_ == DataOneofCase.BattlePack) {
              subBuilder.MergeFrom(BattlePack);
            }
            input.ReadMessage(subBuilder);
            BattlePack = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class LoginPack : pb::IMessage<LoginPack> {
    private static readonly pb::MessageParser<LoginPack> _parser = new pb::MessageParser<LoginPack>(() => new LoginPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LoginPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginPack(LoginPack other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LoginPack Clone() {
      return new LoginPack(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LoginPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LoginPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LoginPack other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ChatPack : pb::IMessage<ChatPack> {
    private static readonly pb::MessageParser<ChatPack> _parser = new pb::MessageParser<ChatPack>(() => new ChatPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatPack(ChatPack other) : this() {
      toUser_ = other.toUser_;
      fromUser_ = other.fromUser_;
      content_ = other.content_;
      chatType_ = other.chatType_;
      timestamp_ = other.timestamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatPack Clone() {
      return new ChatPack(this);
    }

    /// <summary>Field number for the "toUser" field.</summary>
    public const int ToUserFieldNumber = 1;
    private string toUser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ToUser {
      get { return toUser_; }
      set {
        toUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fromUser" field.</summary>
    public const int FromUserFieldNumber = 2;
    private string fromUser_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FromUser {
      get { return fromUser_; }
      set {
        fromUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 3;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chatType" field.</summary>
    public const int ChatTypeFieldNumber = 4;
    private int chatType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChatType {
      get { return chatType_; }
      set {
        chatType_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 5;
    private long timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ToUser != other.ToUser) return false;
      if (FromUser != other.FromUser) return false;
      if (Content != other.Content) return false;
      if (ChatType != other.ChatType) return false;
      if (Timestamp != other.Timestamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ToUser.Length != 0) hash ^= ToUser.GetHashCode();
      if (FromUser.Length != 0) hash ^= FromUser.GetHashCode();
      if (Content.Length != 0) hash ^= Content.GetHashCode();
      if (ChatType != 0) hash ^= ChatType.GetHashCode();
      if (Timestamp != 0L) hash ^= Timestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ToUser.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ToUser);
      }
      if (FromUser.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(FromUser);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Content);
      }
      if (ChatType != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ChatType);
      }
      if (Timestamp != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Timestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ToUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ToUser);
      }
      if (FromUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FromUser);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (ChatType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChatType);
      }
      if (Timestamp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Timestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatPack other) {
      if (other == null) {
        return;
      }
      if (other.ToUser.Length != 0) {
        ToUser = other.ToUser;
      }
      if (other.FromUser.Length != 0) {
        FromUser = other.FromUser;
      }
      if (other.Content.Length != 0) {
        Content = other.Content;
      }
      if (other.ChatType != 0) {
        ChatType = other.ChatType;
      }
      if (other.Timestamp != 0L) {
        Timestamp = other.Timestamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ToUser = input.ReadString();
            break;
          }
          case 18: {
            FromUser = input.ReadString();
            break;
          }
          case 26: {
            Content = input.ReadString();
            break;
          }
          case 32: {
            ChatType = input.ReadInt32();
            break;
          }
          case 40: {
            Timestamp = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FriendInfo : pb::IMessage<FriendInfo> {
    private static readonly pb::MessageParser<FriendInfo> _parser = new pb::MessageParser<FriendInfo>(() => new FriendInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendInfo(FriendInfo other) : this() {
      username_ = other.username_;
      isOnline_ = other.isOnline_;
      isFriend_ = other.isFriend_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendInfo Clone() {
      return new FriendInfo(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    /// <summary>
    ///好友用户名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isOnline" field.</summary>
    public const int IsOnlineFieldNumber = 2;
    private bool isOnline_;
    /// <summary>
    ///是否在线
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsOnline {
      get { return isOnline_; }
      set {
        isOnline_ = value;
      }
    }

    /// <summary>Field number for the "isFriend" field.</summary>
    public const int IsFriendFieldNumber = 3;
    private bool isFriend_;
    /// <summary>
    ///是否已经是好友
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsFriend {
      get { return isFriend_; }
      set {
        isFriend_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (IsOnline != other.IsOnline) return false;
      if (IsFriend != other.IsFriend) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (IsOnline != false) hash ^= IsOnline.GetHashCode();
      if (IsFriend != false) hash ^= IsFriend.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (IsOnline != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsOnline);
      }
      if (IsFriend != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsFriend);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (IsOnline != false) {
        size += 1 + 1;
      }
      if (IsFriend != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendInfo other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.IsOnline != false) {
        IsOnline = other.IsOnline;
      }
      if (other.IsFriend != false) {
        IsFriend = other.IsFriend;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 16: {
            IsOnline = input.ReadBool();
            break;
          }
          case 24: {
            IsFriend = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class FriendPack : pb::IMessage<FriendPack> {
    private static readonly pb::MessageParser<FriendPack> _parser = new pb::MessageParser<FriendPack>(() => new FriendPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FriendPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendPack(FriendPack other) : this() {
      opType_ = other.opType_;
      targetUser_ = other.targetUser_;
      friendList_ = other.friendList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FriendPack Clone() {
      return new FriendPack(this);
    }

    /// <summary>Field number for the "opType" field.</summary>
    public const int OpTypeFieldNumber = 1;
    private global::GameProtocol.FriendOpType opType_ = global::GameProtocol.FriendOpType.FriendOpNone;
    /// <summary>
    /// 操作类型 (获取列表 / 添加 / 删除)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.FriendOpType OpType {
      get { return opType_; }
      set {
        opType_ = value;
      }
    }

    /// <summary>Field number for the "targetUser" field.</summary>
    public const int TargetUserFieldNumber = 2;
    private string targetUser_ = "";
    /// <summary>
    /// 目标用户
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TargetUser {
      get { return targetUser_; }
      set {
        targetUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "friendList" field.</summary>
    public const int FriendListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::GameProtocol.FriendInfo> _repeated_friendList_codec
        = pb::FieldCodec.ForMessage(26, global::GameProtocol.FriendInfo.Parser);
    private readonly pbc::RepeatedField<global::GameProtocol.FriendInfo> friendList_ = new pbc::RepeatedField<global::GameProtocol.FriendInfo>();
    /// <summary>
    /// 好友列表数据 (仅在 opType = GetList 且由服务器返回时，这个列表里才会有数据)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameProtocol.FriendInfo> FriendList {
      get { return friendList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FriendPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FriendPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OpType != other.OpType) return false;
      if (TargetUser != other.TargetUser) return false;
      if(!friendList_.Equals(other.friendList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OpType != global::GameProtocol.FriendOpType.FriendOpNone) hash ^= OpType.GetHashCode();
      if (TargetUser.Length != 0) hash ^= TargetUser.GetHashCode();
      hash ^= friendList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OpType != global::GameProtocol.FriendOpType.FriendOpNone) {
        output.WriteRawTag(8);
        output.WriteEnum((int) OpType);
      }
      if (TargetUser.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TargetUser);
      }
      friendList_.WriteTo(output, _repeated_friendList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OpType != global::GameProtocol.FriendOpType.FriendOpNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OpType);
      }
      if (TargetUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetUser);
      }
      size += friendList_.CalculateSize(_repeated_friendList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FriendPack other) {
      if (other == null) {
        return;
      }
      if (other.OpType != global::GameProtocol.FriendOpType.FriendOpNone) {
        OpType = other.OpType;
      }
      if (other.TargetUser.Length != 0) {
        TargetUser = other.TargetUser;
      }
      friendList_.Add(other.friendList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OpType = (global::GameProtocol.FriendOpType) input.ReadEnum();
            break;
          }
          case 18: {
            TargetUser = input.ReadString();
            break;
          }
          case 26: {
            friendList_.AddEntriesFrom(input, _repeated_friendList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 聊天记录包 (拉取历史记录用)
  /// </summary>
  public sealed partial class ChatHistoryPack : pb::IMessage<ChatHistoryPack> {
    private static readonly pb::MessageParser<ChatHistoryPack> _parser = new pb::MessageParser<ChatHistoryPack>(() => new ChatHistoryPack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ChatHistoryPack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatHistoryPack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatHistoryPack(ChatHistoryPack other) : this() {
      targetUser_ = other.targetUser_;
      chatList_ = other.chatList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ChatHistoryPack Clone() {
      return new ChatHistoryPack(this);
    }

    /// <summary>Field number for the "targetUser" field.</summary>
    public const int TargetUserFieldNumber = 1;
    private string targetUser_ = "";
    /// <summary>
    /// 目标用户(与谁的聊天记录)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TargetUser {
      get { return targetUser_; }
      set {
        targetUser_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chatList" field.</summary>
    public const int ChatListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::GameProtocol.ChatPack> _repeated_chatList_codec
        = pb::FieldCodec.ForMessage(18, global::GameProtocol.ChatPack.Parser);
    private readonly pbc::RepeatedField<global::GameProtocol.ChatPack> chatList_ = new pbc::RepeatedField<global::GameProtocol.ChatPack>();
    /// <summary>
    /// 历史记录列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameProtocol.ChatPack> ChatList {
      get { return chatList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ChatHistoryPack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ChatHistoryPack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TargetUser != other.TargetUser) return false;
      if(!chatList_.Equals(other.chatList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TargetUser.Length != 0) hash ^= TargetUser.GetHashCode();
      hash ^= chatList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TargetUser.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TargetUser);
      }
      chatList_.WriteTo(output, _repeated_chatList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TargetUser.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetUser);
      }
      size += chatList_.CalculateSize(_repeated_chatList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ChatHistoryPack other) {
      if (other == null) {
        return;
      }
      if (other.TargetUser.Length != 0) {
        TargetUser = other.TargetUser;
      }
      chatList_.Add(other.chatList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TargetUser = input.ReadString();
            break;
          }
          case 18: {
            chatList_.AddEntriesFrom(input, _repeated_chatList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 战斗包
  /// </summary>
  public sealed partial class BattlePack : pb::IMessage<BattlePack> {
    private static readonly pb::MessageParser<BattlePack> _parser = new pb::MessageParser<BattlePack>(() => new BattlePack());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattlePack> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePack() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePack(BattlePack other) : this() {
      levelId_ = other.levelId_;
      cardInstanceId_ = other.cardInstanceId_;
      targetEntityId_ = other.targetEntityId_;
      events_ = other.events_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattlePack Clone() {
      return new BattlePack(this);
    }

    /// <summary>Field number for the "levelId" field.</summary>
    public const int LevelIdFieldNumber = 1;
    private int levelId_;
    /// <summary>
    /// 关卡ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int LevelId {
      get { return levelId_; }
      set {
        levelId_ = value;
      }
    }

    /// <summary>Field number for the "cardInstanceId" field.</summary>
    public const int CardInstanceIdFieldNumber = 2;
    private int cardInstanceId_;
    /// <summary>
    /// 卡牌实例ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CardInstanceId {
      get { return cardInstanceId_; }
      set {
        cardInstanceId_ = value;
      }
    }

    /// <summary>Field number for the "targetEntityId" field.</summary>
    public const int TargetEntityIdFieldNumber = 3;
    private int targetEntityId_;
    /// <summary>
    /// 目标实体ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetEntityId {
      get { return targetEntityId_; }
      set {
        targetEntityId_ = value;
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::GameProtocol.BattleEvent> _repeated_events_codec
        = pb::FieldCodec.ForMessage(34, global::GameProtocol.BattleEvent.Parser);
    private readonly pbc::RepeatedField<global::GameProtocol.BattleEvent> events_ = new pbc::RepeatedField<global::GameProtocol.BattleEvent>();
    /// <summary>
    /// 战斗事件列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::GameProtocol.BattleEvent> Events {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattlePack);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattlePack other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LevelId != other.LevelId) return false;
      if (CardInstanceId != other.CardInstanceId) return false;
      if (TargetEntityId != other.TargetEntityId) return false;
      if(!events_.Equals(other.events_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (LevelId != 0) hash ^= LevelId.GetHashCode();
      if (CardInstanceId != 0) hash ^= CardInstanceId.GetHashCode();
      if (TargetEntityId != 0) hash ^= TargetEntityId.GetHashCode();
      hash ^= events_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (LevelId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(LevelId);
      }
      if (CardInstanceId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CardInstanceId);
      }
      if (TargetEntityId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TargetEntityId);
      }
      events_.WriteTo(output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (LevelId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LevelId);
      }
      if (CardInstanceId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CardInstanceId);
      }
      if (TargetEntityId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetEntityId);
      }
      size += events_.CalculateSize(_repeated_events_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattlePack other) {
      if (other == null) {
        return;
      }
      if (other.LevelId != 0) {
        LevelId = other.LevelId;
      }
      if (other.CardInstanceId != 0) {
        CardInstanceId = other.CardInstanceId;
      }
      if (other.TargetEntityId != 0) {
        TargetEntityId = other.TargetEntityId;
      }
      events_.Add(other.events_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            LevelId = input.ReadInt32();
            break;
          }
          case 16: {
            CardInstanceId = input.ReadInt32();
            break;
          }
          case 24: {
            TargetEntityId = input.ReadInt32();
            break;
          }
          case 34: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 单个战斗表现事件
  /// </summary>
  public sealed partial class BattleEvent : pb::IMessage<BattleEvent> {
    private static readonly pb::MessageParser<BattleEvent> _parser = new pb::MessageParser<BattleEvent>(() => new BattleEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattleEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleEvent(BattleEvent other) : this() {
      eventType_ = other.eventType_;
      sourceId_ = other.sourceId_;
      targetId_ = other.targetId_;
      switch (other.EventParamsCase) {
        case EventParamsOneofCase.Damage:
          Damage = other.Damage.Clone();
          break;
        case EventParamsOneofCase.Heal:
          Heal = other.Heal.Clone();
          break;
        case EventParamsOneofCase.Death:
          Death = other.Death.Clone();
          break;
        case EventParamsOneofCase.SkillCast:
          SkillCast = other.SkillCast.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleEvent Clone() {
      return new BattleEvent(this);
    }

    /// <summary>Field number for the "eventType" field.</summary>
    public const int EventTypeFieldNumber = 1;
    private global::GameProtocol.BattleEventType eventType_ = global::GameProtocol.BattleEventType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.BattleEventType EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    /// <summary>Field number for the "sourceId" field.</summary>
    public const int SourceIdFieldNumber = 2;
    private int sourceId_;
    /// <summary>
    /// 事件来源实体ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SourceId {
      get { return sourceId_; }
      set {
        sourceId_ = value;
      }
    }

    /// <summary>Field number for the "targetId" field.</summary>
    public const int TargetIdFieldNumber = 3;
    private int targetId_;
    /// <summary>
    /// 事件目标实体ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TargetId {
      get { return targetId_; }
      set {
        targetId_ = value;
      }
    }

    /// <summary>Field number for the "damage" field.</summary>
    public const int DamageFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.DamageParams Damage {
      get { return eventParamsCase_ == EventParamsOneofCase.Damage ? (global::GameProtocol.DamageParams) eventParams_ : null; }
      set {
        eventParams_ = value;
        eventParamsCase_ = value == null ? EventParamsOneofCase.None : EventParamsOneofCase.Damage;
      }
    }

    /// <summary>Field number for the "heal" field.</summary>
    public const int HealFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.HealParams Heal {
      get { return eventParamsCase_ == EventParamsOneofCase.Heal ? (global::GameProtocol.HealParams) eventParams_ : null; }
      set {
        eventParams_ = value;
        eventParamsCase_ = value == null ? EventParamsOneofCase.None : EventParamsOneofCase.Heal;
      }
    }

    /// <summary>Field number for the "death" field.</summary>
    public const int DeathFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.DeathParams Death {
      get { return eventParamsCase_ == EventParamsOneofCase.Death ? (global::GameProtocol.DeathParams) eventParams_ : null; }
      set {
        eventParams_ = value;
        eventParamsCase_ = value == null ? EventParamsOneofCase.None : EventParamsOneofCase.Death;
      }
    }

    /// <summary>Field number for the "skillCast" field.</summary>
    public const int SkillCastFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::GameProtocol.SkillCastParams SkillCast {
      get { return eventParamsCase_ == EventParamsOneofCase.SkillCast ? (global::GameProtocol.SkillCastParams) eventParams_ : null; }
      set {
        eventParams_ = value;
        eventParamsCase_ = value == null ? EventParamsOneofCase.None : EventParamsOneofCase.SkillCast;
      }
    }

    private object eventParams_;
    /// <summary>Enum of possible cases for the "eventParams" oneof.</summary>
    public enum EventParamsOneofCase {
      None = 0,
      Damage = 4,
      Heal = 5,
      Death = 6,
      SkillCast = 7,
    }
    private EventParamsOneofCase eventParamsCase_ = EventParamsOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventParamsOneofCase EventParamsCase {
      get { return eventParamsCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEventParams() {
      eventParamsCase_ = EventParamsOneofCase.None;
      eventParams_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattleEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattleEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventType != other.EventType) return false;
      if (SourceId != other.SourceId) return false;
      if (TargetId != other.TargetId) return false;
      if (!object.Equals(Damage, other.Damage)) return false;
      if (!object.Equals(Heal, other.Heal)) return false;
      if (!object.Equals(Death, other.Death)) return false;
      if (!object.Equals(SkillCast, other.SkillCast)) return false;
      if (EventParamsCase != other.EventParamsCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EventType != global::GameProtocol.BattleEventType.None) hash ^= EventType.GetHashCode();
      if (SourceId != 0) hash ^= SourceId.GetHashCode();
      if (TargetId != 0) hash ^= TargetId.GetHashCode();
      if (eventParamsCase_ == EventParamsOneofCase.Damage) hash ^= Damage.GetHashCode();
      if (eventParamsCase_ == EventParamsOneofCase.Heal) hash ^= Heal.GetHashCode();
      if (eventParamsCase_ == EventParamsOneofCase.Death) hash ^= Death.GetHashCode();
      if (eventParamsCase_ == EventParamsOneofCase.SkillCast) hash ^= SkillCast.GetHashCode();
      hash ^= (int) eventParamsCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EventType != global::GameProtocol.BattleEventType.None) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EventType);
      }
      if (SourceId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SourceId);
      }
      if (TargetId != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TargetId);
      }
      if (eventParamsCase_ == EventParamsOneofCase.Damage) {
        output.WriteRawTag(34);
        output.WriteMessage(Damage);
      }
      if (eventParamsCase_ == EventParamsOneofCase.Heal) {
        output.WriteRawTag(42);
        output.WriteMessage(Heal);
      }
      if (eventParamsCase_ == EventParamsOneofCase.Death) {
        output.WriteRawTag(50);
        output.WriteMessage(Death);
      }
      if (eventParamsCase_ == EventParamsOneofCase.SkillCast) {
        output.WriteRawTag(58);
        output.WriteMessage(SkillCast);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EventType != global::GameProtocol.BattleEventType.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (SourceId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SourceId);
      }
      if (TargetId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TargetId);
      }
      if (eventParamsCase_ == EventParamsOneofCase.Damage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Damage);
      }
      if (eventParamsCase_ == EventParamsOneofCase.Heal) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Heal);
      }
      if (eventParamsCase_ == EventParamsOneofCase.Death) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Death);
      }
      if (eventParamsCase_ == EventParamsOneofCase.SkillCast) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SkillCast);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattleEvent other) {
      if (other == null) {
        return;
      }
      if (other.EventType != global::GameProtocol.BattleEventType.None) {
        EventType = other.EventType;
      }
      if (other.SourceId != 0) {
        SourceId = other.SourceId;
      }
      if (other.TargetId != 0) {
        TargetId = other.TargetId;
      }
      switch (other.EventParamsCase) {
        case EventParamsOneofCase.Damage:
          if (Damage == null) {
            Damage = new global::GameProtocol.DamageParams();
          }
          Damage.MergeFrom(other.Damage);
          break;
        case EventParamsOneofCase.Heal:
          if (Heal == null) {
            Heal = new global::GameProtocol.HealParams();
          }
          Heal.MergeFrom(other.Heal);
          break;
        case EventParamsOneofCase.Death:
          if (Death == null) {
            Death = new global::GameProtocol.DeathParams();
          }
          Death.MergeFrom(other.Death);
          break;
        case EventParamsOneofCase.SkillCast:
          if (SkillCast == null) {
            SkillCast = new global::GameProtocol.SkillCastParams();
          }
          SkillCast.MergeFrom(other.SkillCast);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EventType = (global::GameProtocol.BattleEventType) input.ReadEnum();
            break;
          }
          case 16: {
            SourceId = input.ReadInt32();
            break;
          }
          case 24: {
            TargetId = input.ReadInt32();
            break;
          }
          case 34: {
            global::GameProtocol.DamageParams subBuilder = new global::GameProtocol.DamageParams();
            if (eventParamsCase_ == EventParamsOneofCase.Damage) {
              subBuilder.MergeFrom(Damage);
            }
            input.ReadMessage(subBuilder);
            Damage = subBuilder;
            break;
          }
          case 42: {
            global::GameProtocol.HealParams subBuilder = new global::GameProtocol.HealParams();
            if (eventParamsCase_ == EventParamsOneofCase.Heal) {
              subBuilder.MergeFrom(Heal);
            }
            input.ReadMessage(subBuilder);
            Heal = subBuilder;
            break;
          }
          case 50: {
            global::GameProtocol.DeathParams subBuilder = new global::GameProtocol.DeathParams();
            if (eventParamsCase_ == EventParamsOneofCase.Death) {
              subBuilder.MergeFrom(Death);
            }
            input.ReadMessage(subBuilder);
            Death = subBuilder;
            break;
          }
          case 58: {
            global::GameProtocol.SkillCastParams subBuilder = new global::GameProtocol.SkillCastParams();
            if (eventParamsCase_ == EventParamsOneofCase.SkillCast) {
              subBuilder.MergeFrom(SkillCast);
            }
            input.ReadMessage(subBuilder);
            SkillCast = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class DamageParams : pb::IMessage<DamageParams> {
    private static readonly pb::MessageParser<DamageParams> _parser = new pb::MessageParser<DamageParams>(() => new DamageParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DamageParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DamageParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DamageParams(DamageParams other) : this() {
      damageValue_ = other.damageValue_;
      isCritical_ = other.isCritical_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DamageParams Clone() {
      return new DamageParams(this);
    }

    /// <summary>Field number for the "damageValue" field.</summary>
    public const int DamageValueFieldNumber = 1;
    private int damageValue_;
    /// <summary>
    /// 伤害数值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DamageValue {
      get { return damageValue_; }
      set {
        damageValue_ = value;
      }
    }

    /// <summary>Field number for the "isCritical" field.</summary>
    public const int IsCriticalFieldNumber = 2;
    private bool isCritical_;
    /// <summary>
    /// 是否暴击
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsCritical {
      get { return isCritical_; }
      set {
        isCritical_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DamageParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DamageParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DamageValue != other.DamageValue) return false;
      if (IsCritical != other.IsCritical) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DamageValue != 0) hash ^= DamageValue.GetHashCode();
      if (IsCritical != false) hash ^= IsCritical.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DamageValue != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(DamageValue);
      }
      if (IsCritical != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsCritical);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DamageValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DamageValue);
      }
      if (IsCritical != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DamageParams other) {
      if (other == null) {
        return;
      }
      if (other.DamageValue != 0) {
        DamageValue = other.DamageValue;
      }
      if (other.IsCritical != false) {
        IsCritical = other.IsCritical;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DamageValue = input.ReadInt32();
            break;
          }
          case 16: {
            IsCritical = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed partial class HealParams : pb::IMessage<HealParams> {
    private static readonly pb::MessageParser<HealParams> _parser = new pb::MessageParser<HealParams>(() => new HealParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<HealParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[9]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HealParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HealParams(HealParams other) : this() {
      healValue_ = other.healValue_;
      isOverHeal_ = other.isOverHeal_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HealParams Clone() {
      return new HealParams(this);
    }

    /// <summary>Field number for the "healValue" field.</summary>
    public const int HealValueFieldNumber = 1;
    private int healValue_;
    /// <summary>
    /// 治疗数值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int HealValue {
      get { return healValue_; }
      set {
        healValue_ = value;
      }
    }

    /// <summary>Field number for the "isOverHeal" field.</summary>
    public const int IsOverHealFieldNumber = 2;
    private bool isOverHeal_;
    /// <summary>
    /// 是否溢出治疗
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsOverHeal {
      get { return isOverHeal_; }
      set {
        isOverHeal_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as HealParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(HealParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (HealValue != other.HealValue) return false;
      if (IsOverHeal != other.IsOverHeal) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HealValue != 0) hash ^= HealValue.GetHashCode();
      if (IsOverHeal != false) hash ^= IsOverHeal.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HealValue != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(HealValue);
      }
      if (IsOverHeal != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsOverHeal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HealValue != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(HealValue);
      }
      if (IsOverHeal != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(HealParams other) {
      if (other == null) {
        return;
      }
      if (other.HealValue != 0) {
        HealValue = other.HealValue;
      }
      if (other.IsOverHeal != false) {
        IsOverHeal = other.IsOverHeal;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            HealValue = input.ReadInt32();
            break;
          }
          case 16: {
            IsOverHeal = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///暂时为空
  /// </summary>
  public sealed partial class DeathParams : pb::IMessage<DeathParams> {
    private static readonly pb::MessageParser<DeathParams> _parser = new pb::MessageParser<DeathParams>(() => new DeathParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeathParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[10]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeathParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeathParams(DeathParams other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeathParams Clone() {
      return new DeathParams(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeathParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeathParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeathParams other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class SkillCastParams : pb::IMessage<SkillCastParams> {
    private static readonly pb::MessageParser<SkillCastParams> _parser = new pb::MessageParser<SkillCastParams>(() => new SkillCastParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SkillCastParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameProtocol.GamesProtocolReflection.Descriptor.MessageTypes[11]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkillCastParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkillCastParams(SkillCastParams other) : this() {
      skillId_ = other.skillId_;
      targetIds_ = other.targetIds_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SkillCastParams Clone() {
      return new SkillCastParams(this);
    }

    /// <summary>Field number for the "skillId" field.</summary>
    public const int SkillIdFieldNumber = 1;
    private int skillId_;
    /// <summary>
    /// 技能ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SkillId {
      get { return skillId_; }
      set {
        skillId_ = value;
      }
    }

    /// <summary>Field number for the "targetIds" field.</summary>
    public const int TargetIdsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_targetIds_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> targetIds_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 多目标
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> TargetIds {
      get { return targetIds_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SkillCastParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SkillCastParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SkillId != other.SkillId) return false;
      if(!targetIds_.Equals(other.targetIds_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SkillId != 0) hash ^= SkillId.GetHashCode();
      hash ^= targetIds_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SkillId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SkillId);
      }
      targetIds_.WriteTo(output, _repeated_targetIds_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SkillId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SkillId);
      }
      size += targetIds_.CalculateSize(_repeated_targetIds_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SkillCastParams other) {
      if (other == null) {
        return;
      }
      if (other.SkillId != 0) {
        SkillId = other.SkillId;
      }
      targetIds_.Add(other.targetIds_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SkillId = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            targetIds_.AddEntriesFrom(input, _repeated_targetIds_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
